version: "3"

services:
  server:
    container_name: "central_worker_service_server"
    build: .
    command: "./main server"
    ports:
      - "9095:9095"
    volumes:
      - /var/local_storage/image/:/var/local_storage/media/image/
  
  worker:
    container_name: "central_worker_service_worker"
    build: .
    command: "./main worker"
    volumes:
      - /var/local_storage/image/:/var/local_storage/media/image/

  telebot:
    container_name: "central_worker_service_telegram_bot"
    build: .
    command: "./main telegram-bot"
    volumes:
      - /var/local_storage/image/:/var/local_storage/media/image/

  siakad_scraper:
    container_name: "central_worker_service_siakad_scraper"
    build: .
    command: "./main siakad-scraper"
    volumes:
      - /var/local_storage/image/:/var/local_storage/media/image/
    
